name: CLA Assistant


on:
  workflow_call:
    secrets:
      CLA_REPO_TOKEN:
        required: true
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, closed, synchronize]


permissions:
  actions: write
  contents: read # signatures are in remote repo
  pull-requests: write
  statuses: write


jobs:
  cla-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Check CLA
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby accept the terms') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_REPO_TOKEN }}
        with:
          path-to-document: 'https://github.com/luneutic/cla/blob/main/CLA.md'
          custom-pr-sign-comment: 'I have read the CLA Document and I hereby accept the terms' # IMPORTANT: Must be the same as above
          lock-pullrequest-aftermerge: true

          # Where to store signatures
          remote-organization-name: luneutic
          remote-repository-name: cla
          path-to-signatures: signatures/cla.json
          branch: main
